[setup]
packages = ["dotnet-sdk_8"]

[phases.build]
cmds = ["dotnet build SkinCareTipsAPI/SkinCareTipsAPI.csproj -c Release"]

[phases.install]
cmds = ["dotnet restore"]

[start]
cmd = "dotnet SkinCareTipsAPI/bin/Release/net8.0/SkinCareTipsAPI.dll"
